#server:
#  port: 8080

spring:
  application:
    name: venda-ingressos

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  app:
    external:
      topic:
        name: venda-ingressos-teste

  datasource:
    url: jdbc:h2:mem:banco
    driverClassName: org.h2.Driver
    username:
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      path: /h2
      enabled: true