#server:
#  port: 8080

spring:
  application:
    name: venda-ingressos

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  app:
    external:
      topic:
        name: venda-ingressos-teste

  datasource:
    url: jdbc:h2:mem:banco
    driverClassName: org.h2.Driver
    username: adm
    password: adm
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    defer-datasource-initialization: true
  h2:
    console:
      path: /h2
      enabled: true

springdoc:
  api-docs:
    path: /api-docs