#server:
#  port: 8080

spring:
  application:
    name: venda-ingressos

  datasource:
    url: jdbc:h2:mem:banco
    driverClassName: org.h2.Driver
    username:
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      path: /h2
      enabled: true